/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package own.exifgui;

import com.fasterxml.jackson.databind.JsonNode;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.File;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;

import java.net.URL;
import java.util.Base64;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Vector;
import javax.net.ssl.HttpsURLConnection;

/**
 *
 * @author satch
 */
public class AddNewLocation extends javax.swing.JFrame {

    /**
     * Creates new form AddNewLocation
     */
    public AddNewLocation(ExifGui2 parent) {
        initComponents();
        this.response = new Vector();
        this.SavedjLabel.setText("____");
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NameTextField = new javax.swing.JTextField();
        LocationTextField = new javax.swing.JTextField();
        LattitudeTextField = new javax.swing.JTextField();
        LongitudeTextField = new javax.swing.JTextField();
        AskOpenStreetmapjButton = new javax.swing.JButton();
        SavejButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SavedjLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);

        NameTextField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                NameTextFieldPropertyChange(evt);
            }
        });
        NameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NameTextFieldKeyTyped(evt);
            }
        });

        LocationTextField.setToolTipText("Budapest Liszt Ferenc ter 2");
        LocationTextField.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                LocationTextFieldCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                LocationTextFieldInputMethodTextChanged(evt);
            }
        });
        LocationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocationTextFieldActionPerformed(evt);
            }
        });
        LocationTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LocationTextFieldKeyTyped(evt);
            }
        });

        LattitudeTextField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                LattitudeTextFieldPropertyChange(evt);
            }
        });
        LattitudeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LattitudeTextFieldKeyTyped(evt);
            }
        });

        LongitudeTextField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                LongitudeTextFieldPropertyChange(evt);
            }
        });
        LongitudeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LongitudeTextFieldKeyTyped(evt);
            }
        });

        AskOpenStreetmapjButton.setText("Ask OpenStreetMap based on this field:");
        AskOpenStreetmapjButton.setEnabled(false);
        AskOpenStreetmapjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AskOpenStreetmapjButtonActionPerformed(evt);
            }
        });

        SavejButton.setText("Save");
        SavejButton.setEnabled(false);
        SavejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavejButtonActionPerformed(evt);
            }
        });

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Location name");

        jLabel3.setText("Lattitude");

        jLabel4.setText("Longitude");

        SavedjLabel.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LattitudeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LongitudeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AskOpenStreetmapjButton))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SavejButton)
                            .addComponent(jButton3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SavedjLabel)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(LattitudeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(LongitudeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SavedjLabel)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AskOpenStreetmapjButton)
                    .addComponent(SavejButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SavejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavejButtonActionPerformed
        String nameb64, locationb64, latb64, lonb64;
        nameb64 = Base64.getEncoder().encodeToString(this.NameTextField.getText().getBytes());
        locationb64 = Base64.getEncoder().encodeToString(this.LocationTextField.getText().getBytes());
        latb64 = Base64.getEncoder().encodeToString(this.LattitudeTextField.getText().getBytes());
        lonb64 = Base64.getEncoder().encodeToString(this.LongitudeTextField.getText().getBytes());
        String savestring = nameb64 + "." + locationb64 + "." + latb64 + "." + lonb64 + "." + System.lineSeparator();
        OwnUtils.appendStrToFile(this.parent.location_filename, savestring);
        this.SavedjLabel.setText("Saved");
        this.parent.LoadLocationList();
    }//GEN-LAST:event_SavejButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void AskOpenStreetmapjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AskOpenStreetmapjButtonActionPerformed
        try {
            String location = this.LocationTextField.getText().trim();
            if (!location.isEmpty()) {
                this.response.clear();
                this.SavedjLabel.setText("____");
                Vector<JsonNode> response = OwnUtils.AskAboutTheLatLOnTheOpenstreetmap(location);
                Vector<String> elements = new Vector();

                Iterator<JsonNode> iter = response.iterator();
                JsonNode node;
                String display_name;
                while (iter.hasNext()) {
                    node = iter.next();
                    display_name = node.get("display_name").asText();
                    this.response.add(node);
                    elements.add(display_name);                    
                }
                DynamicList4Addresses listwindow = new DynamicList4Addresses(elements, this);
                listwindow.pack();
                listwindow.setVisible(true);
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_AskOpenStreetmapjButtonActionPerformed

    private void LocationTextFieldInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_LocationTextFieldInputMethodTextChanged
        
    }//GEN-LAST:event_LocationTextFieldInputMethodTextChanged

    private void LocationTextFieldCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_LocationTextFieldCaretPositionChanged
        
    }//GEN-LAST:event_LocationTextFieldCaretPositionChanged

    private void LocationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocationTextFieldActionPerformed
        
    }//GEN-LAST:event_LocationTextFieldActionPerformed

    private void LocationTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LocationTextFieldKeyTyped
        this.AskOpenStreetmapjButton.setEnabled(!this.LocationTextField.getText().trim().isEmpty());
    }//GEN-LAST:event_LocationTextFieldKeyTyped

    private void NameTextFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_NameTextFieldPropertyChange
        
    }//GEN-LAST:event_NameTextFieldPropertyChange

    private void LattitudeTextFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_LattitudeTextFieldPropertyChange
        
    }//GEN-LAST:event_LattitudeTextFieldPropertyChange

    private void LongitudeTextFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_LongitudeTextFieldPropertyChange
        
    }//GEN-LAST:event_LongitudeTextFieldPropertyChange

    private void LongitudeTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LongitudeTextFieldKeyTyped
        this.ChecktheinputfieldEmptyness();
    }//GEN-LAST:event_LongitudeTextFieldKeyTyped

    private void LattitudeTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LattitudeTextFieldKeyTyped
        this.ChecktheinputfieldEmptyness();        // TODO add your handling code here:
    }//GEN-LAST:event_LattitudeTextFieldKeyTyped

    private void NameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameTextFieldKeyTyped
        this.ChecktheinputfieldEmptyness();        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextFieldKeyTyped
    
    private void ChecktheinputfieldEmptyness() {
        if( (!this.NameTextField.getText().trim().isEmpty()) &&
            (!this.LattitudeTextField.getText().trim().isEmpty()) &&
            (!this.LongitudeTextField.getText().trim().isEmpty())) {
                if (OwnUtils.IsDouble(this.LattitudeTextField.getText().trim()) && 
                    OwnUtils.IsDouble(this.LongitudeTextField.getText().trim())) {
                    this.SavejButton.setEnabled(true);
                    return;
                }
        }
        this.SavejButton.setEnabled(false);
    }
    
    public void setSelectedLatLonObj(int selected) {
        JsonNode snode = this.response.get(selected);
        this.LocationTextField.setText(snode.get("display_name").asText());
        this.LattitudeTextField.setText(snode.get("lat").asText());
        this.LongitudeTextField.setText(snode.get("lon").asText());
        this.ChecktheinputfieldEmptyness();
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AskOpenStreetmapjButton;
    private javax.swing.JTextField LattitudeTextField;
    private javax.swing.JTextField LocationTextField;
    private javax.swing.JTextField LongitudeTextField;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JLabel SavedjLabel;
    private javax.swing.JButton SavejButton;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
    Vector<JsonNode> response;
    ExifGui2 parent;
}
