/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package own.exifgui;

import java.io.File;
import java.io.IOException;
import java.nio.file.DirectoryStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.HashSet;
import java.util.List;
import java.util.ListIterator;
import java.util.Set;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import java.awt.Canvas;
import java.awt.Graphics;
import java.awt.Color;
import java.awt.image.BufferStrategy; 
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;

/**
 *
 * @author satch
 */
public class ExifGui2 extends javax.swing.JFrame {

    /**
     * Creates new form ExifGui2
     */
    public ExifGui2() {
        initComponents();
        allSelectedImagePath = new Vector();
        this.Canvas4Image.createBufferStrategy(1);
        this.bufferStrategy = this.Canvas4Image.getBufferStrategy();
        this.graphics = bufferStrategy.getDrawGraphics();
        this.height = this.Canvas4Image.getHeight();
        this.width = this.Canvas4Image.getWidth();
        this.selectedImageIndex = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        ExitDialog = new javax.swing.JDialog();
        ExitjButton = new javax.swing.JButton();
        CanceljButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList4Places = new javax.swing.JList<>();
        jButtonSavePlacesLIst = new javax.swing.JButton();
        jButtonAppendPlaceToSelected = new javax.swing.JButton();
        jButtonAddNewPlace = new javax.swing.JButton();
        jButtonSaveTheTaggedImages = new javax.swing.JButton();
        Frame4Image = new javax.swing.JInternalFrame();
        Canvas4Image = new java.awt.Canvas();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButtonAddNewPlace1 = new javax.swing.JButton();
        jButtonSavePlacesLIst1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4ImageNames = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList4SelectedImageNames = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonAppendPlaceToSelected1 = new javax.swing.JButton();
        jButtonAppendPlaceToSelected2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();

        ExitjButton.setText("Exit");
        ExitjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitjButtonActionPerformed(evt);
            }
        });

        CanceljButton.setText("Cancel");
        CanceljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CanceljButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ExitDialogLayout = new javax.swing.GroupLayout(ExitDialog.getContentPane());
        ExitDialog.getContentPane().setLayout(ExitDialogLayout);
        ExitDialogLayout.setHorizontalGroup(
            ExitDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExitDialogLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(CanceljButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExitDialogLayout.createSequentialGroup()
                .addContainerGap(299, Short.MAX_VALUE)
                .addComponent(ExitjButton)
                .addGap(29, 29, 29))
        );
        ExitDialogLayout.setVerticalGroup(
            ExitDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExitDialogLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(CanceljButton)
                .addGap(136, 136, 136)
                .addComponent(ExitjButton)
                .addGap(50, 50, 50))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList4Places.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jList4Places);

        jButtonSavePlacesLIst.setText("Save list");
        jButtonSavePlacesLIst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSavePlacesLIstActionPerformed(evt);
            }
        });

        jButtonAppendPlaceToSelected.setText("Append place to selected");

        jButtonAddNewPlace.setText("Add new place");
        jButtonAddNewPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddNewPlaceActionPerformed(evt);
            }
        });

        jButtonSaveTheTaggedImages.setText("Save the tagged images");
        jButtonSaveTheTaggedImages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveTheTaggedImagesActionPerformed(evt);
            }
        });

        Frame4Image.setVisible(true);

        Canvas4Image.setPreferredSize(new java.awt.Dimension(110, 110));

        javax.swing.GroupLayout Frame4ImageLayout = new javax.swing.GroupLayout(Frame4Image.getContentPane());
        Frame4Image.getContentPane().setLayout(Frame4ImageLayout);
        Frame4ImageLayout.setHorizontalGroup(
            Frame4ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Canvas4Image, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1138, Short.MAX_VALUE)
        );
        Frame4ImageLayout.setVerticalGroup(
            Frame4ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Canvas4Image, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
        );

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        jButtonAddNewPlace1.setText("Add new Metadata");
        jButtonAddNewPlace1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddNewPlace1ActionPerformed(evt);
            }
        });

        jButtonSavePlacesLIst1.setText("Save list");
        jButtonSavePlacesLIst1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSavePlacesLIst1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Location");

        jLabel2.setText("Meta data");

        jScrollPane4.setViewportView(jList4ImageNames);

        jList4SelectedImageNames.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList4SelectedImageNamesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList4SelectedImageNames);

        jButton1.setText("Remove from list");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonAppendPlaceToSelected1.setText("Up");
        jButtonAppendPlaceToSelected1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAppendPlaceToSelected1ActionPerformed(evt);
            }
        });

        jButtonAppendPlaceToSelected2.setText("Down");
        jButtonAppendPlaceToSelected2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAppendPlaceToSelected2ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenu1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu1MenuSelected(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Select directory");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jButtonAppendPlaceToSelected2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAppendPlaceToSelected1)
                        .addGap(233, 233, 233)
                        .addComponent(jButtonAppendPlaceToSelected)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSaveTheTaggedImages))
                    .addComponent(Frame4Image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAddNewPlace1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSavePlacesLIst1))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAddNewPlace)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSavePlacesLIst)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1409, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Frame4Image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonAddNewPlace)
                                    .addComponent(jButtonSavePlacesLIst))
                                .addGap(30, 30, 30)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonAddNewPlace1)
                                    .addComponent(jButtonSavePlacesLIst1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSaveTheTaggedImages)
                            .addComponent(jButtonAppendPlaceToSelected)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonAppendPlaceToSelected1)
                                .addComponent(jButtonAppendPlaceToSelected2)))
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(17, 17, 17))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(409, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSavePlacesLIstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSavePlacesLIstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSavePlacesLIstActionPerformed

    private void jButtonAddNewPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddNewPlaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddNewPlaceActionPerformed

    private void jButtonSaveTheTaggedImagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveTheTaggedImagesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSaveTheTaggedImagesActionPerformed

    private void jButtonAddNewPlace1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddNewPlace1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddNewPlace1ActionPerformed

    private void jButtonSavePlacesLIst1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSavePlacesLIst1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSavePlacesLIst1ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu1MenuSelected
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu1MenuSelected

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        String absolute_path;
        fileChooser.setFileSelectionMode( JFileChooser.DIRECTORIES_ONLY);
        this.fileChooser.setToolTipText("Only direcory is selectable.");
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            // What to do with the file, e.g. display it in a TextArea
            //textarea.read( new FileReader( file.getAbsolutePath() ), null );
            System.out.println(file.getAbsolutePath());
            absolute_path = file.getAbsolutePath();
            Set<String> fileSet = new HashSet<>();
            String[] splitted_filename;
            String ext;
            String full_filepath;
            Vector<String> fileVector = new Vector();
            DefaultListModel listModel = new DefaultListModel();
            try (
                    DirectoryStream<Path> stream = Files.newDirectoryStream(Paths.get(absolute_path))) {
                    for (Path path : stream) {
                        if (!Files.isDirectory(path)) {
                            splitted_filename = path.getFileName().toString().split("\\.");                            
                            if (splitted_filename.length == 2) {
                                ext = splitted_filename[1].trim();
                                System.out.println(ext);
                                if (ext.compareToIgnoreCase("jpg") == 0 || ext.compareToIgnoreCase("jpeg") == 0) {
                                    full_filepath = Path.of(absolute_path, path.getFileName().toString()).toString();
                                    fileSet.add(full_filepath);
                                    System.out.println(full_filepath);
                                    fileVector.add(full_filepath);
                                }
                            }
                        }
                    }
                    this.jList4ImageNames.setListData(fileVector);
            } catch (IOException ex) {
                Logger.getLogger(ExifGui2.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            System.out.println("File access cancelled by user.");
        }                
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void ExitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitjButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitjButtonActionPerformed

    private void CanceljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CanceljButtonActionPerformed
        // TODO add your handling code here:
        ExitDialog.setVisible(false);
    }//GEN-LAST:event_CanceljButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        List <String> selected = this.jList4SelectedImageNames.getSelectedValuesList();
        ListIterator<String> li = selected.listIterator();
        String path;
        while(li.hasNext()) {
            path = li.next();
            this.allSelectedImagePath.remove(path);
        }
        this.jList4SelectedImageNames.setListData(this.allSelectedImagePath);       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        List <String> selected = this.jList4ImageNames.getSelectedValuesList();
        ListIterator<String> li = selected.listIterator();
        String path;
        while(li.hasNext()) {
            path = li.next();
            if (!this.allSelectedImagePath.contains(path)) {
                this.allSelectedImagePath.add(path);
            }
        }
        this.jList4SelectedImageNames.setListData(this.allSelectedImagePath);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void changeselectedAndShowImage() {
        int index = this.jList4SelectedImageNames.getSelectedIndex();
        if (this.allSelectedImagePath.size() > 0 && index > -1) {
            String path = this.allSelectedImagePath.get(index);
            File file = new File(path);
            try {
                BufferedImage img = null;
                this.actualImage = ImageIO.read(file);
                if (this.actualImage != null) {
                    this.graphics.drawImage(this.actualImage, 0, 0, this);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }        
        }
    }
    
    private void stepSelectedImage(int direction) {
        int uplimit = this.allSelectedImagePath.size();
        int lowlimit = 0;
        if (uplimit == lowlimit) {
            return;
        }
        int newvalue = this.selectedImageIndex + direction;
        if (newvalue < lowlimit) {
            newvalue = lowlimit;
        } else if (newvalue > uplimit -1 ) {
            newvalue = uplimit -1;
        } 
        if (this.selectedImageIndex == newvalue) {
            return;
        } else {
            this.selectedImageIndex = newvalue;
        }
        this.jList4SelectedImageNames.setSelectedIndex(this.selectedImageIndex);
        this.changeselectedAndShowImage();
    }
    
    private void jButtonAppendPlaceToSelected1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAppendPlaceToSelected1ActionPerformed
        this.stepSelectedImage(-1);
    }//GEN-LAST:event_jButtonAppendPlaceToSelected1ActionPerformed

    private void jButtonAppendPlaceToSelected2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAppendPlaceToSelected2ActionPerformed
        this.stepSelectedImage(1);
    }//GEN-LAST:event_jButtonAppendPlaceToSelected2ActionPerformed

    private void jList4SelectedImageNamesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList4SelectedImageNamesValueChanged
        this.changeselectedAndShowImage();
    }//GEN-LAST:event_jList4SelectedImageNamesValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExifGui2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExifGui2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExifGui2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExifGui2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExifGui2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CanceljButton;
    private java.awt.Canvas Canvas4Image;
    private javax.swing.JDialog ExitDialog;
    private javax.swing.JButton ExitjButton;
    private javax.swing.JInternalFrame Frame4Image;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAddNewPlace;
    private javax.swing.JButton jButtonAddNewPlace1;
    private javax.swing.JButton jButtonAppendPlaceToSelected;
    private javax.swing.JButton jButtonAppendPlaceToSelected1;
    private javax.swing.JButton jButtonAppendPlaceToSelected2;
    private javax.swing.JButton jButtonSavePlacesLIst;
    private javax.swing.JButton jButtonSavePlacesLIst1;
    private javax.swing.JButton jButtonSaveTheTaggedImages;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList4ImageNames;
    private javax.swing.JList<String> jList4Places;
    private javax.swing.JList<String> jList4SelectedImageNames;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables

    private Vector <String> allSelectedImagePath;
    private BufferStrategy bufferStrategy;
    private Graphics graphics;
    private int width, height;
    private BufferedImage actualImage;
    private int selectedImageIndex;
}
